server:
  port: 8765

spring:
  application:
    name: gate-service
    
zuul:
  routes:
    account:
      path: /reinbursments/**
      serviceId: reinbursment-service
      strip-prefix: false
    customer:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false
      